// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { AppleStyleDock } from "./_components/Dock";
import { ThemeProvider } from "@/components/theme-provider"
// import { BackgroundBeamsWithCollision } from "@/components/ui/background-beams-with-collision";
import { Toaster } from "sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { MuseoModerno } from 'next/font/google'
 
// If loading a variable font, you don't need to specify the font weight
const museoModerno = MuseoModerno({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`h-screen w-full ${museoModerno.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          {/* <AppleStyleDock /> */}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
