# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Auto Deploy

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install --include=dev

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>" -r https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git
      env:
        user_name: 'abouramd'
        user_email: 'abouramd@student.1337.ma'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
